# -*- coding: utf-8 -*-
"""indecimal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y8wbszdG7RbNiI9K6ZLmTMxmYijHcgE1
"""

!pip install sentence-transformers langchain-text-splitters faiss-cpu gradio requests

import faiss
import numpy as np
from langchain_text_splitters import RecursiveCharacterTextSplitter
from sentence_transformers import SentenceTransformer


documents = [
    "Policy: Weather Delays. Construction projects must halt if wind speeds exceed 40 mph or during heavy lightning. These delays are non-penalizable.",
    "FAQ: Material shortages. If steel is delayed, contractors must notify the project manager within 48 hours to adjust the timeline.",
    "Spec: Foundation pouring. Concrete foundations must cure for at least 7 days before heavy machinery can operate on them.",
    "Policy: Safety Gear. All personnel on site must wear Class 2 high-visibility vests and hard hats at all times."
]
text_data = " ".join(documents)

text_splitter = RecursiveCharacterTextSplitter(chunk_size=150, chunk_overlap=20)
chunks = text_splitter.split_text(text_data)
print(f"Created {len(chunks)} chunks.")


print("Loading embedding model...")
embedder = SentenceTransformer('all-MiniLM-L6-v2')
embeddings = embedder.encode(chunks)


dimension = embeddings.shape[1]
index = faiss.IndexFlatL2(dimension)
index.add(np.array(embeddings))
print(f"Added {index.ntotal} vectors to the FAISS index.")

import requests
import json
import numpy as np


OPENROUTER_API_KEY = "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"

def retrieve_info(query, k=2):
    """Finds the most relevant chunks using FAISS."""
    query_embedding = embedder.encode([query])
    distances, indices = index.search(np.array(query_embedding), k)
    return [chunks[i] for i in indices[0]]

def generate_answer(query):
    """Retrieves context and asks the LLM to answer."""
    context_chunks = retrieve_info(query)
    context_text = "\n".join(context_chunks)

    system_prompt = f"""
    You are a construction marketplace assistant.
    Answer the user's question using ONLY the provided context below.
    If the answer is not in the context, say "I don't know based on the provided documents."
    Do not hallucinate.

    Context:
    {context_text}
    """

    try:
        response = requests.post(
            url="https://openrouter.ai/api/v1/chat/completions",
            headers={
                "Authorization": f"Bearer {OPENROUTER_API_KEY}",
                "Content-Type": "application/json"
            },
            json={
                "model": "openrouter/free",
                "messages": [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": query}
                ]
            }
        )

        data = response.json()


        if "error" in data:
            return f"OpenRouter API Error: {data['error']['message']}"

        answer = data['choices'][0]['message']['content']

    except Exception as e:
        return f"Code Error: {str(e)}"


    final_output = f"**Answer:**\n{answer}\n\n---\n**Retrieved Context Used:**\n"
    for chunk in context_chunks:
        final_output += f"- {chunk}\n"

    return final_output


print(generate_answer("How long does concrete need to cure?"))

import gradio as gr


interface = gr.Interface(
    fn=generate_answer,
    inputs=gr.Textbox(lines=2, placeholder="Ask a construction question... e.g., 'What happens if wind exceeds 40 mph?'"),
    outputs=gr.Markdown(),
    title="Construction Marketplace RAG Assistant",
    description="Ask questions about internal policies. Answers are strictly grounded in retrieved documents."
)

interface.launch(share=True)

